### ISSUE TITLE
3 errors in error check.

### ISSUE THREAD

**Issue by kolbdog323** [theMK2k/Media-Hoarder#68]
There are three errors in error check today. Plot, parental guide and companies. I have scanned it 10 times in a row the error check same error. Says the persisted  query is not found. Sometimes release info error as well.

**Comment by theMK2k** [comment]
thanks for the report, as soon as I got the chance to take a look, I'll let you know

**Comment by kolbdog323** [comment]
No problem . it takes 5-6 tries rescanning to remove error.

**Comment by kolbdog323** [comment]
now just got the find error again. Every scan check the error result is random.

**Comment by kolbdog323** [comment]
and bluey season 2 error is back for series.

**Comment by kolbdog323** [comment]
every error check random errors.

**Comment by kolbdog323** [comment]
Here are all the error check results currently:
Find (vital to detect the IMDB entry for movies and tv series)
Main Page (Genres, Rating/Votes, Metacritic Score, Poster, Plot Summary, Trailer URL)
Full Plot Summary (Main Page only contains an extract of the full summary)
Plot Keywords
Release Info (Title, Localized Title, Original Title, Year)
Technical Data (Runtime)
Parental Guide (Age Rating, Levels of: Nudity, Violence, Profanity, Alcohol & Drugs, Frightening Scenes)
$IMDB_id_AgeRating_Chosen_Country missing
Credits
Companies
EXCEPTION: { "stack": "Error: GraphQL Error: PersistedQueryNotFound\n at g (app://./js/app.48fc8abd.js:1:809457)\n at Module.A (app://./js/app.48fc8abd.js:1:828414)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async v (app://./js/app.48fc8abd.js:1:123481)\n at async o.runChecks (app://./js/app.48fc8abd.js:1:496211)", "message": "GraphQL Error: PersistedQueryNotFound" }
Filming Locations
EXCEPTION: { "stack": "Error: GraphQL Error: PersistedQueryNotFound\n at g (app://./js/app.48fc8abd.js:1:809457)\n at Module.K (app://./js/app.48fc8abd.js:1:839946)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n at async I (app://./js/app.48fc8abd.js:1:129823)\n at async o.runChecks (app://./js/app.48fc8abd.js:1:496211)", "message": "GraphQL Error: PersistedQueryNotFound" }
Series Episodes
query 'Bluey Season 2' results missing

**Comment by kolbdog323** [comment]
Series error and parental guide went away this time. But every scan the error result is 100% random every 2 scans.

**Comment by theMK2k** [comment]
I can confirm this, I'm also getting PersistedQueryNotFound errors all over the place.

When IMDB updates (parts of) their site, we see these errors and need to adapt. There is currently no way to do this automatically. I'll let you know as soon as I was able to update all of this.

**Comment by kolbdog323** [comment]
> I can confirm this, I'm also getting PersistedQueryNotFound errors all over the place.
> 
> When IMDB updates (parts of) their site, we see these errors and need to adapt. There is currently no way to do this automatically. I'll let you know as soon as I was able to update all of this.

Sounds good appreciate it. I really appreciate al ll the hard work you do on this software. Sorry to always bug you with errors.

**Comment by theMK2k** [comment]
That's all appreciated, reported errors and feature requests can only make the software better ;)

**Comment by theMK2k** [comment]
Today, over the course of 2 hours I did multiple scraper checks and all went OK. Did you experience the same?

**Comment by kolbdog323** [comment]
Same here

**Comment by theMK2k** [comment]
thanks. So this time it seems IMDB "just" had some hickups and nothing really was updated or A/B tested in different regions. I'll keep this issue open and do more tests later. If it stays OK for all tests, we might close it then.
